---
- name: "Add new line elasticsearch.yml"
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    insertafter: "{{ item.exp }}"
    line: "{{ item.line }}"
  with_items:
    - { exp: '^#network.host*', line: '{{ ansible_fqdn }}' }
