---
- name: "Creation du dossier pattern"
  file:
    path: /etc/logstash/patterns
    state: directory
    mode: 0775
    
- name: "On copie les fichiers patterns"
  copy:
    src: "{{ item }}"
    dest: /etc/logstash/patterns/
  with_fileglob: "patterns/*"
