---
#- name: "On vérifie que la stack ELK est installé A FAIRE quand conf OK"

- import_tasks: logstash-patterns.yml
  tags: [ 'logstash' ]
- import_tasks: logstash-instances.yml
  tags: [ 'logstash' ]
- import_tasks: elastic-config.yml
  tags: [ 'elastic' ]
- import_tasks: kibana-config.yml
  tags: [ 'kibana' ]
